# Generated by Django 5.2.1 on 2025-06-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
                ('email', models.CharField()),
                ('phone_num', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
