# Generated by Django 5.2.3 on 2025-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.IntegerField(max_length=10),
        ),
    ]
