# Generated by Django 5.2.3 on 2025-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_student_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=13),
        ),
    ]
